name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write  # Allows interaction with repository projects
      issues: write                # Allows interaction with issues

    env:
      GITHUB_TOKEN: ${{ secrets.COMPANY_REPO_ACTIONS_TOKEN }}

    steps:
      - name: Add the issue to the project
        uses: actions/github-script@v6
        with:
          script: |
            const orgName = "JonCodyDev-Services";  // Your organization name
            const projectId = 4;  // Explicitly use the Project ID '4' here
            const issueNumber = ${{ github.event.issue.number }};
            
            // Directly access the project using its ID
            const project = await github.rest.projects.get({
              project_id: projectId  // Use the project ID directly
            });

            // Get the columns of the project
            const projectColumns = await github.rest.projects.listColumns({
              project_id: projectId,  // Refer to the project ID explicitly
            });
            
            // Find the "Todo" column (exact match with "Todo")
            const todoColumn = projectColumns.data.find(column => column.name === "Todo");

            if (todoColumn) {
              // Add the issue to the "Todo" column
              await github.rest.projects.createCard({
                column_id: todoColumn.id,  // Column ID for "Todo"
                content_id: issueNumber,
                content_type: 'Issue'
              });
            } else {
              console.log('Todo column not found');
            }
