name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.COMPANY_REPO_ACTIONS_TOKEN }}

    steps:
      - name: Add the issue to the project
        uses: actions/github-script@v6
        with:
          script: |
            const orgName = "JonCodyDev-Services";  // Your organization name
            const projectId = 4;  // Your project ID
            const issueNumber = ${{ github.event.issue.number }};

            // Get all projects for the organization
            const projects = await github.rest.projects.listForOrg({
              org: orgName, // Organization name
            });

            // Find the specific project by its ID
            const project = projects.data.find(p => p.id === projectId);

            if (!project) {
              throw new Error(`Project with ID ${projectId} not found in the organization.`);
            }

            // Get the columns of the project
            const projectColumns = await github.rest.projects.listColumns({
              project_id: project.id, // Use the correct project ID
            });

            // Find the "Todo" column
            const todoColumn = projectColumns.data.find(column => column.name === "Todo");

            if (todoColumn) {
              // Add the issue to the "Todo" column
              await github.rest.projects.createCard({
                column_id: todoColumn.id,  // Column ID for "Todo"
                content_id: issueNumber,
                content_type: 'Issue'
              });
            } else {
              console.log('Todo column not found');
            }
