name: Add Issue to Project

on:
  issues:
    types: [opened]  # Trigger the action when an issue is opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add the issue to the project
        uses: actions/github-script@v6
        with:
          script: |
            const projectId = 4; // Your project ID from the URL
            const issueNumber = ${{ github.event.issue.number }};
            
            // Get the columns of the project
            const projectColumns = await github.projects.listColumns({
              project_id: projectId
            });
            
            // Find the "Todo" column (exact match with "Todo")
            const todoColumn = projectColumns.data.find(column => column.name === "Todo");
            
            if (todoColumn) {
              // Add the issue to the "Todo" column
              await github.projects.createCard({
                column_id: todoColumn.id,  // Column ID for "Todo"
                content_id: issueNumber,
                content_type: 'Issue'
              });
            } else {
              console.log('Todo column not found');
            }
