name: Query Projects V2

on:
  push:
    branches:
      - main

jobs:
  query-projects:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      issues: write
      repository-projects: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Query Projects V2 via GraphQL
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const repoOwner = "JonCodyDev-Services";
            const repoName = "company-repo-2";

            const query = `
              query {
                repository(owner: "${repoOwner}", name: "${repoName}") {
                  projectsV2(first: 10) {
                    nodes {
                      id
                      title
                      views(first: 10) {
                        nodes {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            `;

            try {
              const response = await github.graphql(query);
              console.log('Projects V2:', response.repository.projectsV2.nodes);

              if (response.repository.projectsV2.nodes.length === 0) {
                console.log('No Projects found.');
              } else {
                response.repository.projectsV2.nodes.forEach(project => {
                  console.log(`Project: ${project.title}`);
                  project.views.nodes.forEach(view => {
                    console.log(`  View: ${view.name}`);
                  });
                });
              }
            } catch (error) {
              console.error('Error querying Projects V2:', error);
            }