name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.COMPANY_REPO_ACTIONS_TOKEN }}

    steps:
      - name: Add the issue to the project
        uses: actions/github-script@v6
        with:
          script: |
            const orgName = "JonCodyDev-Services";  // Your organization name
            const projectName = "proj2";  // Your project name
            const issueNumber = ${{ github.event.issue.number }};
            
            // Get all projects for the organization
            const projects = await github.rest.projects.listForOrg({
              org: orgName,
            });

            // Find the project with the name 'proj2'
            const project = projects.data.find(p => p.name === projectName);

            if (!project) {
              // If the project is not found in the organization, try fetching from repository-level projects
              const repoName = 'your-repo-name';  // Replace with your repo name

              const repoProjects = await github.rest.projects.listForRepo({
                owner: orgName,
                repo: repoName,
              });

              const repoProject = repoProjects.data.find(p => p.name === projectName);

              if (!repoProject) {
                throw new Error(`Project with name "${projectName}" not found in the organization or repository.`);
              }

              project = repoProject;  // Switch to the repository-level project
            }

            // Get the columns of the project
            const projectColumns = await github.rest.projects.listColumns({
              project_id: project.id,
            });
            
            // Find the "Todo" column (exact match with "Todo")
            const todoColumn = projectColumns.data.find(column => column.name === "Todo");

            if (todoColumn) {
              // Add the issue to the "Todo" column
              await github.rest.projects.createCard({
                column_id: todoColumn.id,  // Column ID for "Todo"
                content_id: issueNumber,
                content_type: 'Issue'
              });
            } else {
              console.log('Todo column not found');
            }
