name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.COMPANY_REPO_ACTIONS_TOKEN }}

    steps:
      - name: Add the issue to the project
        uses: actions/github-script@v6
        with:
          script: |
            const orgName = "JonCodyDev-Services";  // Your organization name
            const projectId = 4;  // Your project ID
            const issueNumber = ${{ github.event.issue.number }};
            
            // Get the columns of the project (organization-level project)
            const projectColumns = await github.rest.projects.listColumns({
              project_id: projectId,  // Use project_id directly
              org: orgName            // Reference the org for organization-level project
            });
            
            // Find the "Todo" column (exact match with "Todo")
            const todoColumn = projectColumns.data.find(column => column.name === "Todo");

            if (todoColumn) {
              // Add the issue to the "Todo" column
              await github.rest.projects.createCard({
                column_id: todoColumn.id,  // Column ID for "Todo"
                content_id: issueNumber,
                content_type: 'Issue'
              });
            } else {
              console.log('Todo column not found');
            }
