name: Add Issue to Project

on:
  issues:
    types: [opened]  # Trigger the action when an issue is opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add the issue to the project
        uses: peter-evans/add-issue-to-project@v2
        with:
          project-url: 'https://github.com/orgs/JonCodyDev-Services/projects/4'  # URL of your project
          issue-number: ${{ github.event.issue.number }}  # The issue number of the opened issue
