name: Query Projects V2

on:
  push:
    branches:
      - main

jobs:
  query-projects:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Adjust if needed
      issues: write
      repository-projects: read  # Allow read access to Projects

    steps:
      - name: Query Projects V2 via GraphQL
        uses: actions/github-script@v6
        with:
          script: |
            const repoOwner = "JonCodyDev-Services";  // Your organization name
            const repoName = "company-repo-2";  // Your repository name

            const query = `
              query {
                repository(owner: "${repoOwner}", name: "${repoName}") {
                  projectsV2(first: 10) {
                    nodes {
                      id
                      title
                      views(first: 10) {
                        nodes {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            `;

            const response = await github.graphql(query);

            console.log('Projects V2:', response.repository.projectsV2.nodes);

            // Optionally, process the response here if needed
            if (response.repository.projectsV2.nodes.length === 0) {
              console.log('No Projects found.');
            } else {
              response.repository.projectsV2.nodes.forEach(project => {
                console.log(`Project: ${project.title}`);
                project.views.nodes.forEach(view => {
                  console.log(`  View: ${view.name}`);
                });
              });
            }
