name: Test Project Columns

on:
  push:
    branches:
      - main

jobs:
  test-project-columns:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.COMPANY_REPO_ACTIONS_TOKEN }}

    steps:
      - name: List Project Columns
        uses: actions/github-script@v6
        with:
          script: |
            const orgName = "JonCodyDev-Services";  // Your organization name
            const projectName = "Your-Project-Name";  // Your project name (replace with actual project name)
            
            // Get all projects for the organization
            const projects = await github.rest.projects.listForOrg({
              org: orgName,
            });

            const project = projects.data.find(p => p.name === projectName);

            if (!project) {
              throw new Error(`Project with name "${projectName}" not found in the organization.`);
            }

            // Get the columns of the project
            const projectColumns = await github.rest.projects.listColumns({
              project_id: project.id,
            });

            console.log('Project Columns:', projectColumns.data);
